echo epub:
time pandoc --epub-stylesheet=./Stylesheets/Global.css --toc --smart -t epub ./Cover.txt ./010_Dedication.txt ./015_Thanks.txt ./020_Part1Marker.txt ./030_Motivations.txt ./040_Three_Essential_Tools.txt ./050_Its_Not_a_Test.txt ./060_Statement_First_Programming.txt ./070_Practicing_What_We_Already_Learned.txt ./080_Sorting_out_the_bits.txt ./090_How_to_start.txt ./100_Analysis_In_TDD.txt ./110_Constrained_Non_Determinism.txt ./120_What_is_the_scope_of_a_Statement_in_TDD.txt ./130_Boundaries.txt ./140_Triangulation.txt ./150_Part2Marker.txt ./160_Composable_Design.txt ./170_TellDoNotAsk.txt ./End.txt ./180_Web_of_objects_explained.txt ./190_Why\ do\ we\ need\ composability.txt ./200_What_does_it_mean_to_compose_objects.txt ./210_How_are_objects_composed.txt ./220_Weaker_and_better_composabiity.txt --epub-cover-image="./Images/cover.png"  -o all.epub
echo
echo
echo html:
time pandoc --toc --standalone --highlight-style=kate --smart -t html ./010_Dedication.txt ./015_Thanks.txt ./020_Part1Marker.txt ./030_Motivations.txt ./040_Three_Essential_Tools.txt ./050_Its_Not_a_Test.txt ./060_Statement_First_Programming.txt ./070_Practicing_What_We_Already_Learned.txt ./080_Sorting_out_the_bits.txt ./090_How_to_start.txt ./100_Analysis_In_TDD.txt ./110_Constrained_Non_Determinism.txt ./120_What_is_the_scope_of_a_Statement_in_TDD.txt ./130_Boundaries.txt ./140_Triangulation.txt ./150_Part2Marker.txt ./160_Composable_Design.txt ./170_TellDoNotAsk.txt ./End.txt ./180_Web_of_objects_explained.txt ./190_Why\ do\ we\ need\ composability.txt ./200_What_does_it_mean_to_compose_objects.txt ./210_How_are_objects_composed.txt ./220_Weaker_and_better_composabiity.txt --css="./Stylesheets/Global.css" -o all.html 
echo
echo
echo odt:
time pandoc --toc --smart -t odt ./010_Dedication.txt ./015_Thanks.txt ./020_Part1Marker.txt ./030_Motivations.txt ./040_Three_Essential_Tools.txt ./050_Its_Not_a_Test.txt ./060_Statement_First_Programming.txt ./070_Practicing_What_We_Already_Learned.txt ./080_Sorting_out_the_bits.txt ./090_How_to_start.txt ./100_Analysis_In_TDD.txt ./110_Constrained_Non_Determinism.txt ./120_What_is_the_scope_of_a_Statement_in_TDD.txt ./130_Boundaries.txt ./140_Triangulation.txt ./150_Part2Marker.txt ./160_Composable_Design.txt ./170_TellDoNotAsk.txt ./End.txt ./180_Web_of_objects_explained.txt ./190_Why\ do\ we\ need\ composability.txt ./200_What_does_it_mean_to_compose_objects.txt ./210_How_are_objects_composed.txt ./220_Weaker_and_better_composabiity.txt --css="./Stylesheets/Global.css" -o all.odt

