# This code was generated by dot2ruby.g

require 'rubygems'
require 'graphviz'
graph_g = GraphViz.digraph( "G" ) { |graph_g|
  graph_g[:fontsize] = '5'
  graph_g[:overlap] = 'false'
  graph_g[:splines] = 'true'
  node_o1 = graph_g.add_nodes( "o1", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o1", "o3", :len => '', :style => '' )
  node_o2 = graph_g.add_nodes( "o2", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o2", "o13", :len => '', :style => 'dashed' )
  node_o3 = graph_g.add_nodes( "o3", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o3", "o2", :len => '', :style => '' )
  graph_g.add_edges( "o3", "o7", :len => '', :style => '' )
  node_o4 = graph_g.add_nodes( "o4", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o4", "o3", :len => '', :style => '' )
  node_o5 = graph_g.add_nodes( "o5", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o5", "o4", :len => '', :style => '' )
  node_o6 = graph_g.add_nodes( "o6", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o6", "o5", :len => '', :style => '' )
  node_o7 = graph_g.add_nodes( "o7", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o7", "o6", :len => '', :style => '' )
  graph_g.add_edges( "o7", "o8", :len => '1.1', :style => '' )
  graph_g.add_edges( "o7", "o11", :len => '', :style => '' )
  node_o8 = graph_g.add_nodes( "o8", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o8", "o9", :len => '', :style => '' )
  node_o9 = graph_g.add_nodes( "o9", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o9", "o14", :len => '', :style => 'dashed' )
  node_o10 = graph_g.add_nodes( "o10", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o10", "o6", :len => '', :style => '' )
  node_o11 = graph_g.add_nodes( "o11", :fontsize => '10', :label => '', :shape => 'circle', :style => '' )
  graph_g.add_edges( "o11", "o9", :len => '', :style => '' )
  graph_g.add_edges( "o11", "o10", :len => '', :style => '' )
  node_o12 = graph_g.add_nodes( "o12", :fontsize => '10', :label => '', :shape => '', :style => 'invisible' )
  graph_g.add_edges( "o12", "o1", :len => '', :style => 'dashed' )
  node_o13 = graph_g.add_nodes( "o13", :fontsize => '10', :label => '', :shape => '', :style => 'invisible' )
  node_o14 = graph_g.add_nodes( "o14", :fontsize => '10', :label => '', :shape => '', :style => 'invisible' )
}.output(:svg => "WebOfObjects.svg")
